baseURL = ""
title= "BooqNow"
pygmentsstyle= 'monokai'
paginate= 50
theme= "localstore"
languageCode = "en-us"
DefaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[params]
  author = "BooqNow"
  description = "❤️ This is an initiation to curate all the available services all over Nepal, let it be drinking water, or medicines or, gases or groceries. So if you are a service provider or you know any services being available in this situation kindly list here. #supportLocalsNepal #healTheDisruptions ❤️"
  github = ""
  facebook = ""
  og_image = "/img/site-banner.jpg"
  sitename = "Booqnow"
  twitter = ""

[languages]
  [languages.en]
  languageName = "English"
  languageCode = "en-us"
  weight = 1
